import { LengthUnit } from '@global/enums/length-unit.enum';
import { ShipmentStatus } from '@global/enums/shipment-status.enum';
import { TrackingState } from '@global/enums/tracking-state.enum';
import { WeightUnit } from '@global/enums/weight-unit.enum';
import { AddressCardAddressVM } from '@global/interfaces/address/address.vm';
import { Costs } from '@global/interfaces/costs.interface';
import { ChargeableWeightDialogPackageVM } from '@global/interfaces/package.vm';
import { ShipmentTaskStates } from '@global/interfaces/shipment-task-states.vm';
import { ShipmentHistory } from '@global/interfaces/shipments/shipment-history.vm';
import { ShipmentInvoiceVM } from '@global/interfaces/shipments/shipment-invoices.vm';
import { ShipmentTaskDataVM } from '@global/interfaces/shipments/shipment-task-data.vm';
import { TrackingItemLogVM } from '@global/interfaces/tracking/tracking-item-log.vm';
import { LineItem } from '@global/modules/common-quote/interfaces/line-item.interface';
import { MessageButtonUserVM } from '@global/modules/message-button/user.vm';
import { MessageEnvelopeMessageVM } from '@global/modules/message-envelope/message.vm';
import { ShipmentStatusUpdates } from '@modules/shipments/interfaces/shipment-status-updates.vm';
import { CbShipmentDocumentVM } from '@modules/shipments/interfaces/cb-shipment-document.vm';
import { FreightType, InvoiceStatusRollup, InvoicingTermParameter, OrderType } from '@CitT/data';

export interface ShipmentDetailsShipmentVM {
  id: string;
  name: string;
  shipmentName: string;
  freightId: string;
  references: string[];
  destination: string;
  orderType: OrderType;
  owner: string;
  contacts: { id: string; name: string }[];
  trackingState?: TrackingState;
  shipmentTaskStates?: ShipmentTaskStates;
  statusUpdates: ShipmentStatusUpdates;
  status: ShipmentStatus;
  mappedStatus: string;
  subStatus?: string;
  from: string;
  value: number;
  estimatedWeight: number;
  estimatedWeightUnit: WeightUnit;
  lineItems?: LineItem[];
  packages: ChargeableWeightDialogPackageVM[];
  lengthUnit: LengthUnit;
  transitTime: string;
  customsDates: string;
  pickUpAddress: AddressCardAddressVM[];
  deliveryAddresses: AddressCardAddressVM[];
  numberOfLocations: number;
  shipmentProvider: string;
  tasks?: ShipmentTaskDataVM[];
  messages?: MessageEnvelopeMessageVM[];
  documents?: CbShipmentDocumentVM[];
  invoices?: ShipmentInvoiceVM[];
  totalCosts?: Costs;
  logs?: TrackingItemLogVM[];
  history: ShipmentHistory[];
  note?: string;
  defaultTeamMember: MessageButtonUserVM;
  liabilityCoverFeeEnabled: boolean;
  trackingNumber?: string;
  newStatusDate?: string;
  preferredFreightMethod?: FreightType;
  ciTotal?: number;
  totalValueAppliedOnCustomerInvoice?: number;
  selectedShipmentMethod: FreightType;
  invoiceStatusRollup: InvoiceStatusRollup;
  ClientCurrencyInput: string;
  StoreFeesAvailable: boolean;
  Valuation_Method__c: string;
  nameOfAddressedEntity: { id: string; name: string };
  invoicingTerm?: InvoicingTermParameter;
  totalOutstandingTasks?: number;
}
